# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
loader_version=0.19.3
loom_version=1.17.16

# Mod Properties
mod_version=1.0.9.1
maven_group=top.s1metro.s1mtr

# Dependencies
fabric_api_version=0.92.11+1.20.1
mtr_version=7916237
modmenu_version=9.0.0
