org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
neo_version=21.1.243
neo_version_range=[21.1.233,)
loader_version_range=[4,)

mod_id=s1mtraddon
mod_name=S1 MTR Addon
mod_license=MIT
mod_version=1.2.3-neoforge.1
mod_group_id=top.s1metro.s1mtr
mod_authors=s1metro; NeoForge 1.21.1 port
mod_description=Adds editable rail speed limits, delayed door opening, and delayed departure to Minecraft Transit Railway.

mtr_modrinth_project=XKPAmI6u
mtr_modrinth_version=9SDO8rYc
mtr_version_range=[4.1.0-beta.2,4.2)
